### PR TITLE
Fix/build command to work around possible cmake bug

### PR DESCRIPTION
**Pull request by HannesSommer**
@ffurrer , yesterday I've gave it another quick shot and believe to have found something. Let's see what Jenkins does out of it.

### CODE REVIEW

**Comment by HannesSommer** [comment]
I've added the test-config (already renamed to xenial-test-config) commit status, which is generate on Xenial.

**Comment by HannesSommer** [comment]
It seems in deed to fix it. The new errors are OpenCV related : http://129.132.38.183:8080/job/test_iclcv_catkin/3/parsed_console/

**Comment by HannesSommer** [comment]
According to documentation the default for the `BUILD_COMMAND` is `cmake --build`. To set it explicitly to this **default** actually works as well! But it does not handle make's jobserver properly and yields sequential make for the wrapped project. 
This current suggestion passes down the jobserver information properly.

**Comment by ffurrer** [comment]
@HannesSommer thanks a ton!

**Comment by ffurrer** [comment]
incorporated changes in #4 Thanks @HannesSommer

**Pull request closed without merging**
